import { createHash } from 'node:crypto';
import { lstat, mkdir, open, readFile, readdir, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { createPatch } from 'diff';
import { CliError } from './config.mjs';

const release = JSON.parse(await readFile(new URL('../package.json', import.meta.url))).version;
const hash = (data) => createHash('sha256').update(data).digest('hex');
const manifestPath = '.edge-commerce/manifest.json';
const allowed = (name) =>
  name &&
  !path.isAbsolute(name) &&
  name.split(/[\\/]/).every((segment) => segment !== '.' && segment !== '..' && segment !== '');
const issue = (code, message) => new CliError(code, message);

async function stat(file) {
  try {
    return await lstat(file);
  } catch (error) {
    if (error.code === 'ENOENT' || error.code === 'ENOTDIR') return null;
    throw error;
  }
}

async function ensureSafe(target, relative) {
  if (!allowed(relative)) throw issue('CONFLICT', `Unsafe destination: ${relative}`);
  let current = target;
  const parts = relative.split('/');
  for (const [index, part] of parts.entries()) {
    current = path.join(current, part);
    const info = await stat(current);
    if (info?.isSymbolicLink() || (info && index < parts.length - 1 && !info.isDirectory())) {
      throw issue('CONFLICT', `Unsafe destination ancestor: ${relative}`);
    }
  }
}

async function filesIn(root, relative = '') {
  const items = await readdir(path.join(root, relative), { withFileTypes: true });
  const results = [];
  for (const item of items) {
    const name = [relative, item.name].filter(Boolean).join('/');
    if (!allowed(name) || item.isSymbolicLink())
      throw issue('OPERATION', `Unsafe template entry: ${name}`);
    if (item.isDirectory()) results.push(...(await filesIn(root, name)));
    else if (item.isFile()) results.push(name);
    else throw issue('OPERATION', `Unsupported template entry: ${name}`);
  }
  return results.sort();
}

async function manifestFor(target) {
  await ensureSafe(target, manifestPath);
  try {
    const bytes = await readFile(path.join(target, manifestPath));
    const data = JSON.parse(bytes);
    if (
      data.version !== 1 ||
      typeof data.files !== 'object' ||
      !data.files ||
      Array.isArray(data.files)
    )
      throw Error('Invalid manifest');
    for (const [name, item] of Object.entries(data.files)) {
      if (
        !allowed(name) ||
        !/^[0-9a-f]{64}$/.test(item.hash) ||
        !['cart-core', 'cart-checkout', 'pdp'].includes(item.feature)
      )
        throw Error('Invalid manifest entry');
    }
    return { data, fingerprint: hash(bytes) };
  } catch (error) {
    if (error.code === 'ENOENT')
      return { data: { version: 1, release, files: {} }, fingerprint: null };
    throw issue('OPERATION', `Cannot read install manifest: ${error.message}`);
  }
}

function configFile(value) {
  return `// Customer-owned configuration generated by edge-commerce; edit for your storefront.\nexport default ${JSON.stringify(value, null, 2)};\n`;
}

export async function planInstall({ templates, target, setup, mode = 'init' }) {
  const root = path.resolve(target);
  if (!(await stat(root))?.isDirectory())
    throw issue('INVALID_INPUT', 'Target must be an existing directory.');
  const { data: previous, fingerprint } = await manifestFor(root);
  if (mode === 'upgrade' && !Object.keys(previous.files).length) {
    throw issue('INVALID_INPUT', 'No Edge Commerce installation to upgrade.');
  }

  // Resolve all feature files before inspecting customer destinations.
  const features = ['cart-core', ...setup.features];
  const planned = new Map();
  for (const feature of features) {
    let names;
    try {
      names = await filesIn(path.join(templates, feature));
    } catch (error) {
      if (error.code === 'ENOENT')
        throw issue('OPERATION', `Missing ${feature} template; starter is not complete.`);
      throw error;
    }
    if (!names.length)
      throw issue('OPERATION', `Empty ${feature} template; starter is not complete.`);
    for (const name of names) {
      if (planned.has(name)) throw issue('OPERATION', `Duplicate template destination: ${name}`);
      planned.set(name, { content: await readFile(path.join(templates, feature, name)), feature });
    }
  }
  if (
    planned.has('scripts/commerce/site-config.js') ||
    planned.has('scripts/commerce/checkout-config.js')
  ) {
    throw issue('OPERATION', 'Config destination must not also appear in a template.');
  }

  // Site config belongs to the shared cart core; checkout config is feature-specific.
  const shared = {
    ...setup.site,
    cartDestination: setup.site.cartDestination || setup.routes?.cart || null,
    cartBehavior: setup.site.cartBehavior || 'navigate',
    productSource: setup.productSource,
  };
  planned.set('scripts/commerce/site-config.js', {
    content: Buffer.from(configFile(shared)),
    feature: 'cart-core',
  });
  if (setup.features.includes('cart-checkout')) {
    planned.set('scripts/commerce/checkout-config.js', {
      content: Buffer.from(
        configFile({
          api: setup.api,
          country: setup.site.country,
          routes: setup.routes,
          paypal: setup.paypal,
        }),
      ),
      feature: 'cart-checkout',
    });
  }

  // A single conflict blocks the entire plan, so classify every destination first.
  const operations = [];
  for (const [name, item] of [...planned].sort(([a], [b]) => a.localeCompare(b))) {
    let action;
    let reason;
    let content = item.content;
    try {
      await ensureSafe(root, name);
      const existing = await stat(path.join(root, name));
      const previousEntry = previous.files[name];
      if (!existing) {
        action = 'add';
        reason = 'new file';
      } else if (!existing.isFile()) {
        action = 'conflict';
        reason = 'destination is not a regular file';
      } else {
        const bytes = await readFile(path.join(root, name));
        const currentHash = hash(bytes);
        if (
          name === 'scripts/commerce/site-config.js' &&
          previousEntry &&
          currentHash === previousEntry.hash
        ) {
          // Shared site config is generated once and never overwritten when adding a feature.
          content = bytes;
          action = 'unchanged';
          reason = 'reusing installed site config';
        } else if (
          currentHash === hash(content) &&
          previousEntry &&
          previousEntry.hash === currentHash
        ) {
          action = 'unchanged';
          reason = 'already installed';
        } else if (
          mode === 'upgrade' &&
          previousEntry &&
          previousEntry.hash === currentHash &&
          previousEntry.feature === item.feature
        ) {
          action = 'update';
          reason = 'upstream change (local file is unmodified)';
          item.diff = createPatch(
            name,
            bytes.toString('utf8'),
            content.toString('utf8'),
            undefined,
            undefined,
            { context: 3 },
          );
          item.old = bytes;
        } else {
          action = 'conflict';
          reason = previousEntry
            ? 'locally changed or upstream version differs; merge manually'
            : 'existing customer file; merge manually';
          if (mode === 'upgrade' && previousEntry)
            item.diff = createPatch(
              name,
              bytes.toString('utf8'),
              content.toString('utf8'),
              undefined,
              undefined,
              { context: 3 },
            );
        }
      }
    } catch (error) {
      if (error.code !== 'CONFLICT') throw error;
      action = 'conflict';
      reason = error.message;
    }
    operations.push({
      path: name,
      feature: item.feature,
      action,
      reason,
      hash: hash(content),
      ...(item.diff ? { diff: item.diff } : {}),
    });
    item.content = content;
  }

  const looksLikeEds =
    (await stat(path.join(root, 'scripts/scripts.js')))?.isFile() ||
    (await stat(path.join(root, 'blocks')))?.isDirectory();
  const result = {
    version: 1,
    outcome: operations.some((op) => op.action === 'conflict') ? 'blocked' : 'ready',
    features: setup.features,
    operations,
    errors: operations
      .filter((op) => op.action === 'conflict')
      .map((op) => ({ path: op.path, message: op.reason })),
    nextSteps: [
      ...(!looksLikeEds
        ? ['Confirm the target directory is an EDS storefront before applying']
        : []),
      ...(operations.some((op) => op.action === 'conflict')
        ? ['Resolve listed conflicts manually, then rerun dry-run']
        : []),
      'Author and publish the documented commerce pages',
      ...(setup.features.includes('cart-checkout')
        ? ['Configure server-side PayPal review settings before live checkout']
        : []),
    ],
  };

  Object.defineProperty(result, 'internal', {
    value: { templates, target: root, setup, planned, fingerprint, previous, mode },
  });
  return result;
}

export async function applyPlan(plan) {
  if (plan.outcome !== 'ready')
    throw issue('CONFLICT', 'Resolve conflicts before applying the plan.');
  const { templates, target, setup, planned, fingerprint, previous, mode } = plan.internal;
  // Re-plan against the current filesystem before making any changes.
  const fresh = await planInstall({ templates, target, setup, mode });
  if (
    fresh.outcome !== 'ready' ||
    fresh.internal.fingerprint !== fingerprint ||
    JSON.stringify(fresh.operations) !== JSON.stringify(plan.operations)
  )
    throw issue('CONFLICT', 'Destination changed since the plan; run dry-run again.');
  const created = [];
  try {
    // Keep original contents for rollback if an operational error interrupts apply.
    for (const op of plan.operations) {
      if (op.action !== 'add' && op.action !== 'update') continue;
      await ensureSafe(target, op.path);
      const dest = path.join(target, op.path);
      await mkdir(path.dirname(dest), { recursive: true });
      if (op.action === 'update') {
        const old = await readFile(dest);
        if (hash(old) !== previous.files[op.path]?.hash)
          throw issue('CONFLICT', `Destination changed during upgrade: ${op.path}`);
        const tempFile = `${dest}.edge-commerce-${process.pid}-${Date.now()}.tmp`;
        try {
          const handle = await open(tempFile, 'wx');
          try {
            await handle.writeFile(planned.get(op.path).content);
          } finally {
            await handle.close();
          }
          await rename(tempFile, dest);
        } finally {
          await rm(tempFile, { force: true });
        }
        created.push({ dest, hash: op.hash, old });
      } else {
        const handle = await open(dest, 'wx');
        created.push({ dest, hash: op.hash });
        try {
          await handle.writeFile(planned.get(op.path).content);
        } finally {
          await handle.close();
        }
      }
    }

    const files = { ...previous.files };
    for (const op of plan.operations) files[op.path] = { feature: op.feature, hash: op.hash };
    const folder = path.join(target, '.edge-commerce');
    await mkdir(folder, { recursive: true });
    const temp = path.join(folder, `manifest-${process.pid}-${Date.now()}.tmp`);
    try {
      const handle = await open(temp, 'wx');
      try {
        await handle.writeFile(`${JSON.stringify({ version: 1, release, files }, null, 2)}\n`);
      } finally {
        await handle.close();
      }
      const latest = await manifestFor(target);
      if (latest.fingerprint !== fingerprint)
        throw issue('CONFLICT', 'Manifest changed since plan.');
      await rename(temp, path.join(target, manifestPath));
    } finally {
      await rm(temp, { force: true });
    }
  } catch (error) {
    for (const item of created.reverse()) {
      try {
        if (hash(await readFile(item.dest)) === item.hash) {
          if (item.old) await writeFile(item.dest, item.old);
          else await rm(item.dest);
        }
      } catch {
        /* Keep an altered file. */
      }
    }
    if (error.code === 'EEXIST' || error.code === 'ELOOP')
      throw issue('CONFLICT', 'Destination changed during install; retry after reviewing files.');
    throw error;
  }
  return { ...plan, outcome: 'applied', nextSteps: plan.nextSteps };
}

export async function planRemoval({ target, features }) {
  const root = path.resolve(target);
  if (!(await stat(root))?.isDirectory())
    throw issue('INVALID_INPUT', 'Target must be an existing directory.');
  if (
    !Array.isArray(features) ||
    !features.length ||
    features.some((name) => !['cart-checkout', 'pdp'].includes(name))
  )
    throw issue('INVALID_INPUT', 'Select cart-checkout and/or pdp to remove.');
  const { data, fingerprint } = await manifestFor(root);
  const installed = new Set(Object.values(data.files).map((entry) => entry.feature));
  if (features.some((name) => !installed.has(name)))
    throw issue('INVALID_INPUT', 'The selected feature is not installed.');
  const remaining = ['cart-checkout', 'pdp'].filter(
    (name) => installed.has(name) && !features.includes(name),
  );
  const selected = new Set(features);
  if (!remaining.length) selected.add('cart-core');

  // Locally edited files become customer-owned and are preserved.
  const operations = [];
  for (const [name, entry] of Object.entries(data.files).sort(([a], [b]) => a.localeCompare(b))) {
    if (!selected.has(entry.feature)) continue;
    let action = 'preserve';
    try {
      await ensureSafe(root, name);
      const bytes = await readFile(path.join(root, name));
      if (hash(bytes) === entry.hash) action = 'delete';
    } catch (error) {
      if (error.code === 'ENOENT') action = 'missing';
      else if (error.code !== 'CONFLICT') throw error;
    }
    operations.push({
      path: name,
      feature: entry.feature,
      action,
      reason:
        action === 'preserve'
          ? 'customer-edited or unsafe; kept for manual review'
          : 'installed file',
    });
  }
  const result = {
    version: 1,
    outcome: 'ready',
    features,
    operations,
    errors: [],
    nextSteps: operations.some((op) => op.action === 'preserve')
      ? ['Manually review preserved customer files']
      : [],
  };
  Object.defineProperty(result, 'internal', { value: { root, features, fingerprint, data } });
  return result;
}

export async function applyRemoval(plan) {
  const { root, features, fingerprint, data } = plan.internal;
  const fresh = await planRemoval({ target: root, features });
  if (
    fresh.internal.fingerprint !== fingerprint ||
    JSON.stringify(fresh.operations) !== JSON.stringify(plan.operations)
  ) {
    throw issue('CONFLICT', 'Files changed since the removal plan; run dry-run again.');
  }
  const removed = [];
  try {
    // Only files still matching their recorded hashes are safe to delete.
    for (const op of plan.operations.filter((item) => item.action === 'delete')) {
      await ensureSafe(root, op.path);
      const dest = path.join(root, op.path);
      const bytes = await readFile(dest);
      if (hash(bytes) !== data.files[op.path].hash)
        throw issue('CONFLICT', `Destination changed: ${op.path}`);
      await rm(dest);
      removed.push({ dest, bytes });
    }
    const files = { ...data.files };
    for (const op of plan.operations) delete files[op.path];
    const current = await manifestFor(root);
    if (current.fingerprint !== fingerprint)
      throw issue('CONFLICT', 'Manifest changed during removal.');
    const dest = path.join(root, manifestPath);
    if (Object.keys(files).length) {
      const temp = `${dest}.${process.pid}-${Date.now()}.tmp`;
      try {
        await writeFile(temp, `${JSON.stringify({ ...data, files, release }, null, 2)}\n`, {
          flag: 'wx',
        });
        await rename(temp, dest);
      } finally {
        await rm(temp, { force: true });
      }
    } else await rm(dest);
  } catch (error) {
    for (const item of removed.reverse()) {
      try {
        if (!(await stat(item.dest))) await writeFile(item.dest, item.bytes, { flag: 'wx' });
      } catch {
        /* Keep any concurrent customer file. */
      }
    }
    throw error;
  }
  return { ...plan, outcome: 'applied' };
}

export async function checkInstall({ target }) {
  const root = path.resolve(target);
  const { data } = await manifestFor(root);
  if (!Object.keys(data.files).length)
    throw issue('INVALID_INPUT', 'No installed Edge Commerce manifest found.');
  const operations = [];
  for (const [name, entry] of Object.entries(data.files).sort(([a], [b]) => a.localeCompare(b))) {
    let action = 'unchanged';
    try {
      await ensureSafe(root, name);
      const current = await readFile(path.join(root, name));
      if (hash(current) !== entry.hash) action = 'modified';
    } catch (error) {
      if (error.code === 'ENOENT') action = 'missing';
      else if (error.code === 'CONFLICT') action = 'modified';
      else throw error;
    }
    operations.push({ path: name, feature: entry.feature, action });
  }
  return {
    version: 1,
    outcome: operations.some((op) => op.action !== 'unchanged') ? 'blocked' : 'ready',
    features: [
      ...new Set(
        Object.values(data.files)
          .map((item) => item.feature)
          .filter((name) => name !== 'cart-core'),
      ),
    ].sort(),
    operations,
    errors: operations
      .filter((op) => op.action !== 'unchanged')
      .map((op) => ({ path: op.path, message: op.action })),
    nextSteps: ['Confirm authored page routes and server-side PayPal settings manually'],
  };
}
